/*
 * Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  ChannelEntity,
  ChannelJoinRuleEntity,
  ChannelSortOrderEntity,
  PublicChannelJoinRuleEntity,
  PublicChannelSearchResultEntity,
} from './channelEntity'
import { Input } from '../../../../public/secureCommsClient'
import { PowerLevelsEntity } from '../common/powerLevelsEntity'

/**
 * Input for `ChannelService.create` method.
 *
 * @interface CreateChannelInput
 * @property {string} selfHandleId Identifier associated with the handle of the creator of the channel.
 * @property {string} name Optional display name for the channel.
 * @property {string} description Optional description of the channel.
 * @property {ChannelJoinRuleEntity} joinRule The rule for joining and whether the channel is searchable.
 * @property {string[]} tags Tags associated with the channel to facilitate searching.
 * @property {string[]} invitedHandleIds The identifiers of the handles to invite immediately when the channel is created.
 * @property {PowerLevelsEntity} powerLevels The minimum levels required to perform each action and the default level of handles in the channel.
 * @property {string} avatarUrl Optional avatar image URL.
 */
export interface CreateChannelInput {
  selfHandleId: string
  name?: string
  description?: string
  joinRule: ChannelJoinRuleEntity
  tags: string[]
  invitedHandleIds: string[]
  powerLevels?: PowerLevelsEntity
  avatarUrl?: string
}

/**
 * Input for `ChannelService.update` method.
 *
 * @interface UpdateChannelInput
 * @property {string} selfHandleId Identifier associated with the handle of the creator of the channel.
 * @property {string} channelId Identifier of the channel to update.
 * @property {Input<string | undefined>} name The display name for the channel. Undefined means do not change.
 * @property {Input<string | undefined>} description The description of the channel. Undefined means do not change.
 * @property {Input<string[]>} tags Tags associated with the channel to facilitate searching. Undefined means do not change.
 * @property {Input<ChannelJoinRuleEntity>} joinRule The rule for joining and whether the channel is searchable. Undefined
 *  means do not change.
 * @property {Input<string | undefined>} avatarUrl The avatar URL of the channel. Undefined means do not change.
 */
export interface UpdateChannelInput {
  selfHandleId: string
  channelId: string
  name?: Input<string | undefined>
  description?: Input<string | undefined>
  tags?: Input<string[]>
  joinRule?: Input<ChannelJoinRuleEntity>
  avatarUrl?: Input<string | undefined>
}

/**
 * Input for `ChannelService.delete` method.
 *
 * @interface DeleteChannelInput
 * @property {string} selfHandleId Identifier associated with the handle of the creator of the channel.
 * @property {string} channelId Identifier associated with the channel to delete.
 */
export interface DeleteChannelInput {
  selfHandleId: string
  channelId: string
}

/**
 * Output for `ChannelsService.list` method.
 *
 * @interface ListChannelsOutput
 * @property {ChannelEntity[]} channels The list of channels retrieved in this query.
 * @property {string[]} unprocessedIds The list of identifiers that were not retrieved but should be retried.
 */
export interface ListChannelsOutput {
  channels: ChannelEntity[]
  unprocessedIds: string[]
}

/**
 * Input for `ChannelsService.search` method.
 *
 * @interface SearchPublicChannelsInput
 * @property {string} selfHandleId Identifier associated with the handle of the creator of the channel.
 * @property {ChannelSortOrderEntity} order Specifies the ordering that should be applied to the
 *  channels returned by the search.
 * @property {string} searchTerm The search string to search metadata such as name, topic, alias etc.
 * @property {PublicChannelJoinRuleEntity} joinRule The rule for joining the public channel.
 * @property {boolean} isJoined Flag to only return joined channels when true or not yet joined
 *  channels when false. If undefined, the flag is not applied to the search.
 * @property {string[]} tags Tags associated with the public channel to facilitate searching. Undefined means do not change.
 * @property {number} limit Number of records to return.
 * @property {string} nextToken A token generated by a previous call to `ChannelsService.search`.
 *  This allows for pagination.
 */
export interface SearchPublicChannelsInput {
  selfHandleId: string
  order: ChannelSortOrderEntity
  searchTerm?: string
  joinRule?: PublicChannelJoinRuleEntity
  isJoined?: boolean
  tags?: string[]
  limit?: number
  nextToken?: string
}

/**
 * Output for `ChannelsService.search` method.
 *
 * @interface SearchPublicChannelsOutput
 * @property {PublicChannelSearchResultEntity[]} channels The list of channel result items retrieved in this search.
 * @property {string} nextToken A token generated by a previous call. This allows for pagination.
 */
export interface SearchPublicChannelsOutput {
  channels: PublicChannelSearchResultEntity[]
  nextToken?: string
}

/**
 * Core entity representation of a channel service used in business logic. Used to perform CRUD operations for channels.
 *
 * @interface ChannelsService
 */
export interface ChannelsService {
  /**
   * Create a channel.
   *
   * @param {CreateChannelInput} input Parameters used to create a channel.
   * @returns {ChannelEntity} The channel that was created.
   */
  create(input: CreateChannelInput): Promise<ChannelEntity>

  /**
   * Retrieve a channel.
   *
   * @param {string} channelId The identifier used to retrieve the desired channel.
   * @returns {ChannelEntity | undefined} The retrieved channel, or undefined if not found.
   */
  get(channelId: string): Promise<ChannelEntity | undefined>

  /**
   * Update a channel.
   *
   * @param {UpdateChannelInput} input Parameters used to update a channel.
   * @returns {ChannelEntity} The channel that was updated.
   */
  update(input: UpdateChannelInput): Promise<ChannelEntity>

  /**
   * Delete a channel.
   *
   * @param {string} input Parameters used to delete a channel.
   */
  delete(input: DeleteChannelInput): Promise<void>

  /**
   * Retrieve a list of channels.
   *
   * @param {string[]} ids A list of identifers used to retrieve the desired channels.
   * @returns {ListChannelsOutput} A list of channels matching the search criteria and
   *  any unprocessed channel identifiers.
   */
  list(ids: string[]): Promise<ListChannelsOutput>

  /**
   * Search for public channels based on search criteria.
   *
   * @param {SearchPublicChannelsInput} input Parameters used to search for a public channel.
   * @returns {SearchPublicChannelsOutput} A list of public channels matching the search criteria.
   *  Can be empty if no channels found
   */
  search(input: SearchPublicChannelsInput): Promise<SearchPublicChannelsOutput>
}
