/*
 * Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { HandleEntity, OwnedHandleEntity } from './handleEntity'

/**
 * Input for `HandleService.update` method.
 *
 * @interface UpdateHandleInput
 * @property {string} handleId Identifier of the handle to update.
 * @property {string} name The new name of the handle.
 */
export interface UpdateHandleInput {
  handleId: string
  name: string
}

/**
 * Input for `HandlesService.list` method.
 *
 * @interface ListHandlesInput
 * @property {number} limit Number of records to return.
 * @property {string} nextToken A token generated by a previous call to `HandlesService.list`.
 *  This allows for pagination.
 */
export interface ListHandlesInput {
  limit?: number
  nextToken?: string
}

/**
 * Output for `HandlesService.list` method.
 *
 * @interface ListHandlesOutput
 * @property {OwnedHandleEntity[]} handles The list of handles retrieved in this query.
 * @property {string} nextToken A token generated by a previous call. This allows for pagination.
 */
export interface ListHandlesOutput {
  handles: OwnedHandleEntity[]
  nextToken?: string
}

/**
 * Core entity representation of a handle service used in business logic. Used to perform CRUD operations for handles.
 *
 * @interface HandleService
 */
export interface HandleService {
  /**
   * Retrieve a handle by its name.
   *
   * @param {string} name The name of the handle to retrieve.
   * @returns {HandleEntity | undefined} The retrieved public handle information, or undefined if not found.
   */
  get(name: string): Promise<HandleEntity | undefined>

  /**
   * Update a handle with new metadata.
   *
   * @param {UpdateHandleInput} input Parameters used to update a handle.
   * @returns {OwnedHandleEntity} The handle that was updated.
   */
  update(input: UpdateHandleInput): Promise<OwnedHandleEntity>

  /**
   * Delete a handle.
   *
   * @param {string} id Identifier associated with the handle to delete.
   * @returns {OwnedHandleEntity} The handle that was deleted.
   */
  delete(id: string): Promise<OwnedHandleEntity>

  /**
   * Retrieve a list of handles.
   *
   * @param {ListHandlesInput} input Parameters used to list handles.
   * @returns {ListHandlesOutput} A list of all handles matching the search criteria. Can be empty if no handles found.
   */
  list(input: ListHandlesInput): Promise<ListHandlesOutput>
}
