/*
 * Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  DefaultLogger,
  DefaultSudoKeyManager,
  Logger,
  NotAuthorizedError,
  SudoCryptoProvider,
  SudoKeyManager,
} from '@sudoplatform/sudo-common'
import {
  SudoUserClient,
  internal as SudoUserInternal,
} from '@sudoplatform/sudo-user'
import { WebSudoCryptoProvider } from '@sudoplatform/sudo-web-crypto-provider'
import {
  DefaultGroupsModule,
  DefaultMessagingModule,
  DefaultNotificationsModule,
  DefaultSecurityModule,
  DefaultStorageModule,
  GroupsModule,
  MessagingModule,
  NotificationsModule,
  SecurityModule,
  StorageModule,
  StorageProviderFactory,
} from './modules'
import { ChannelsModule, DefaultChannelsModule } from './modules/channelsModule'
import {
  DefaultDirectChatsModule,
  DirectChatsModule,
} from './modules/directChatsModule'
import { DefaultHandlesModule, HandlesModule } from './modules/handlesModule'
import { DefaultMediaModule, MediaModule } from './modules/mediaModule'
import { HandleId } from './typings'
import { ApiClient } from '../private/data/common/apiClient'
import {
  SecureCommsServiceConfig,
  getSecureCommsServiceConfig,
} from '../private/data/common/config'
import { PrivateSecureCommsClientOptions } from '../private/data/common/privateSecureCommsClientOptions'
import { DefaultMediaCredentialService } from '../private/data/media/defaultMediaCredentialService'
import { MediaCredentialManager } from '../private/data/media/mediaCredentialManager'
import { DefaultSessionService } from '../private/data/session/defaultSessionService'
import { SessionManager } from '../private/data/session/sessionManager'

/**
 * Pagination interface designed to be extended for list interfaces.
 *
 * @interface Pagination
 * @property {number} limit Number of items to return. Will be defaulted if omitted.
 * @property {string} nextToken A token generated by a previous call.
 */
export interface Pagination {
  limit?: number
  nextToken?: string
}

/**
 * Wrapper for input fields to indicate that they are being modified (as opposed to not modified).
 *
 * @interface Input
 * @property {T} value
 */
export interface Input<T> {
  value: T
}

/**
 * Properties required to upload an avatar.
 *
 * @interface AvatarInput
 * @property {ArrayBuffer} file The media file to upload as an avatar.
 * @property {string} fileName The name of the media file.
 * @property {string} fileType The MIME type of the media file.
 */
export interface AvatarInput {
  file: ArrayBuffer
  fileName: string
  fileType: string
}

export interface SecureCommsClient {
  /**
   * Accessor for the Handles sub-module.
   */
  handles: HandlesModule

  /**
   * Accessor for the Direct Chats sub-module.
   */
  directChats: DirectChatsModule

  /**
   * Accessor for the Groups sub-module.
   */
  groups: GroupsModule

  /**
   * Accessor for the Channels sub-module.
   */
  channels: ChannelsModule

  /**
   * Accessor for the Messaging sub-module.
   */
  messaging: MessagingModule

  /**
   * Accessor for the Media sub-module.
   */
  media: MediaModule

  /**
   * Accessor for the Security sub-module.
   */
  security: SecurityModule

  /**
   * Accessor for the Notifications sub-module.
   */
  notifications: NotificationsModule

  /**
   * Accessor for the Storage sub-module.
   */
  storage: StorageModule

  /**
   * Start syncing in the background for data updates.
   *
   * Can only be called after sign-in creation of a handle.
   *
   * @param {HandleId} handleId Identifier of the handle owned by this client.
   */
  startSyncing(handleId: HandleId): Promise<void>

  /**
   * Check if the client has finished the initial sync and is ready for use.
   *
   * @param {HandleId} handleId Identifier of the handle owned by this client.
   * @returns {boolean} True if the client is ready for use, false if not.
   */
  isReady(handleId: HandleId): Promise<boolean>

  /**
   * Stop syncing.
   *
   * @param {HandleId} handleId Identifier of the handle owned by this client.
   */
  stopSyncing(handleId: HandleId): Promise<void>

  /**
   * Removes any cached data maintained by this client.
   */
  reset(): Promise<void>
}

export type SecureCommsClientOptions = {
  /** Sudo User client to use. No default */
  sudoUserClient: SudoUserClient

  /** SudoCryptoProvider to use. Default is to create a WebSudoCryptoProvider */
  sudoCryptoProvider?: SudoCryptoProvider

  /** SudoKeyManager to use. Default is to create a DefaultSudoKeyManager */
  sudoKeyManager?: SudoKeyManager

  /** StorageProviderFactory to use. Default is undefined, which will make the client use in-memory storage. */
  storageProviderFactory?: StorageProviderFactory

  /** AutoRefreshTokenMinutesBeforeExpiration to use. Default is 5 minutes. Set to 0 to disable automatic token refresh. */
  autoRefreshTokenMinutesBeforeExpiration?: number
}

export class DefaultSecureCommsClient implements SecureCommsClient {
  public handles: HandlesModule
  public directChats: DirectChatsModule
  public groups: GroupsModule
  public channels: ChannelsModule
  public messaging: MessagingModule
  public media: MediaModule
  public security: SecurityModule
  public notifications: NotificationsModule
  public storage: StorageModule

  private readonly apiClient: ApiClient
  private readonly userClient: SudoUserClient
  private readonly sessionService: DefaultSessionService
  private readonly sessionManager: SessionManager
  private readonly mediaCredentialService: DefaultMediaCredentialService
  private readonly mediaCredentialManager: MediaCredentialManager
  private readonly sudoCryptoProvider: SudoCryptoProvider
  private readonly keyManager: SudoKeyManager
  private readonly storageProviderFactory: StorageProviderFactory | undefined
  private readonly identityServiceConfig: SudoUserInternal.IdentityServiceConfig
  private readonly secureCommsServiceConfig: SecureCommsServiceConfig
  private readonly log: Logger

  public constructor(opts: SecureCommsClientOptions) {
    this.log = new DefaultLogger(this.constructor.name)

    const privateOptions = opts as PrivateSecureCommsClientOptions

    this.identityServiceConfig =
      privateOptions.identityServiceConfig ??
      SudoUserInternal.getIdentityServiceConfig().identityService

    this.secureCommsServiceConfig =
      privateOptions.secureCommsServiceConfig ?? getSecureCommsServiceConfig()

    this.storageProviderFactory = opts.storageProviderFactory
    this.storage = new DefaultStorageModule(this.storageProviderFactory)

    this.apiClient = privateOptions.apiClient ?? new ApiClient()
    this.userClient = opts.sudoUserClient
    this.sudoCryptoProvider =
      opts.sudoCryptoProvider ??
      new WebSudoCryptoProvider(
        'SecureCommsClient',
        'com.sudoplatform.appservicename',
      )

    this.keyManager =
      opts.sudoKeyManager ?? new DefaultSudoKeyManager(this.sudoCryptoProvider)

    this.sessionService = new DefaultSessionService(this.apiClient)
    this.sessionManager = new SessionManager(
      this.sessionService,
      this.storage,
      opts.autoRefreshTokenMinutesBeforeExpiration ?? 5,
    )

    this.mediaCredentialService = new DefaultMediaCredentialService(
      this.apiClient,
    )
    this.mediaCredentialManager = new MediaCredentialManager(
      this.userClient,
      this.mediaCredentialService,
      this.identityServiceConfig,
      this.secureCommsServiceConfig,
    )

    this.handles = new DefaultHandlesModule(this.apiClient, this.sessionManager)
    this.directChats = new DefaultDirectChatsModule(this.sessionManager)
    this.groups = new DefaultGroupsModule(
      this.apiClient,
      this.sessionManager,
      this.mediaCredentialManager,
      this.secureCommsServiceConfig,
    )
    this.channels = new DefaultChannelsModule(
      this.apiClient,
      this.sessionManager,
      this.mediaCredentialManager,
      this.secureCommsServiceConfig,
    )
    this.messaging = new DefaultMessagingModule(
      this.sessionManager,
      this.mediaCredentialManager,
      this.secureCommsServiceConfig,
    )
    this.media = new DefaultMediaModule(
      this.sessionManager,
      this.mediaCredentialManager,
      this.secureCommsServiceConfig,
    )
    this.security = new DefaultSecurityModule(this.sessionManager)
    this.notifications = new DefaultNotificationsModule(this.sessionManager)
  }

  public async startSyncing(id: HandleId): Promise<void> {
    if (!(await this.userClient.isSignedIn())) {
      throw new NotAuthorizedError()
    }

    const matrixClient = await this.sessionManager.getMatrixClient(id)
    await matrixClient.startSyncing()
  }

  public async isReady(id: HandleId): Promise<boolean> {
    const matrixClient = await this.sessionManager.getMatrixClient(id)
    return matrixClient.isReady()
  }

  public async stopSyncing(id: HandleId): Promise<void> {
    const matrixClient = await this.sessionManager.getMatrixClient(id)
    await matrixClient.stopSyncing()
  }

  public async reset(): Promise<void> {
    await this.keyManager.removeAllKeys()
    await this.sessionManager.reset()
  }
}
